server:
  port: 8003

#mybatis配置
mybatis:
  type-aliases-package: com.dizhongdi.pojo
  config-location: classpath:myabtis/mybatis-config.xml
  mapper-locations: classpath:myabtis/mapper/*.xml

  #spring的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db03?serverTimezone=UTC
    username: root
    password: asdw14
  application:
    name: springcloud-provider-dept

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8003

#info配置（就是提示信息，通过actuator监控可以看到）
info:
  app.name: dizhongdi-springcloud
  company.name: www.dizhongdi.com