server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # fetch-registry如果为false，则表示自己为注册中心
  instance:
    hostname: localhost